// services/backlogEvents.ts
export const BACKLOG_EVENTS = {
  USER_CREATED_NOTE: "user_created_note",
  USER_DELETED_NOTE: "user_deleted_note",
  USER_CREATED_QUIZ: "user_created_quiz",
  USER_HOSTED_QUIZ_SESSION: "user_hosted_quiz_session",
  USER_STARTED_QUIZ_SESSION: "user_started_quiz_session",
  USER_SHARED_NOTE: "user_shared_note",
  USER_JOINED_NOTE: "user_joined_note",
  USER_SHARED_QUIZ_SESSION: "user_shared_quiz_session",
  USER_USED_AI: "user_used_AI",
  USER_USED_OCR: "user_used_OCR",
  LOGIN_SESSION: "login_session",
  USER_SAVED_NOTE: "user_saved_note",
  USER_OPENED_NOTE_EDITOR: "user_opened_note_editor",
  USER_VIEWED_SHARED_NOTE: "user_viewed_shared_note",
  USER_OPENED_NOTEBOOK: "user_opened_notebook",
  USER_UPDATED_NOTEBOOK_SETTINGS: "user_updated_notebook_settings",
  USER_CREATED_NOTEBOOK: "user_created_notebook",
  USER_DELETED_NOTEBOOK: "user_deleted_notebook",
  USER_UPDATED_PROPERTIES: "user_updated_properties",
  USER_VIEWED_PUBLIC_NOTEBOOK: "user_viewed_public_notebook",
  USER_VIEWED_PUBLIC_NOTE: "user_viewed_public_note",
  USER_CREATED_MULTIPLAYER_SESSION: "user_created_multiplayer_session",
  USER_JOINED_MULTIPLAYER_SESSION: "user_joined_multiplayer_session",
  USER_LEFT_MULTIPLAYER_SESSION: "user_left_multiplayer_session",
  USER_TOGGLED_READY_IN_MULTIPLAYER: "user_toggled_ready_in_multiplayer",
  USER_STARTED_MULTIPLAYER_QUIZ: "user_started_multiplayer_quiz",
  USER_COMPLETED_MULTIPLAYER_QUIZ: "user_completed_multiplayer_quiz",
  USER_LEFT_MULTIPLAYER_GAME: "user_left_multiplayer_game",
  USER_GENERATED_QUIZ_WITH_AI: "user_generated_quiz_with_ai",
  USER_SAVED_QUIZ: "user_saved_quiz",
  USER_STARTED_QUIZ: "user_started_quiz",
  USER_COMPLETED_QUIZ: "user_completed_quiz",
  USER_EDITED_QUIZ: "user_edited_quiz",
  USER_DELETED_QUIZ: "user_deleted_quiz",
  USER_VIEWED_QUIZ_RESULTS: "user_viewed_quiz_results",
  USER_SEARCHED_USERS:"user_search_user",
  USER_SENT_FRIEND_REQUEST:"user_sent_friend_request",
  USER_ACCEPTED_FRIEND_REQUEST: "user_accepted_friend_request",
  USER_REJECTED_FRIEND_REQUEST: "user_rejected_friend_request",
  USER_UPDATED_QUIZ: "user_updated_quiz",
  USER_VIEWED_QUIZ: "user_viewed_quiz",
  USER_VIEWED_QUIZ_LIST: "user_viewed_quiz_list",
  USER_EDIT_QUIZ: "user_edit_quiz"
} as const;

export type BacklogEvent = typeof BACKLOG_EVENTS[keyof typeof BACKLOG_EVENTS];
