// File: scripts/journey-setup.ts
// Admin script to populate journey quizzes and levels
// Run this once to set up your educational journey system

import { JourneyQuiz, JourneyService, Level } from '../services/journey-service';

/**
 * Educational Journey Quizzes
 * 10 levels covering Math, Science, English, General Knowledge, and Philippine History
 */
const JOURNEY_QUIZZES: Omit<JourneyQuiz, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // ============================================
  // LEVEL 1 - Basic Math (Easy)
  // ============================================
  {
    title: 'Numbers and Basic Operations',
    description: 'Master the fundamentals of addition and subtraction',
    difficulty: 'easy',
    estimatedTime: 300, // 5 minutes
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        question: 'What is 5 + 7?',
        options: ['10', '11', '12', '13'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Addition',
        points: 1,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        question: 'What is 15 - 8?',
        options: ['6', '7', '8', '9'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Subtraction',
        points: 1,
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        question: 'What is 3 × 4?',
        options: ['7', '10', '12', '15'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Multiplication',
        points: 1,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        question: 'What is 20 ÷ 4?',
        options: ['4', '5', '6', '8'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Division',
        points: 1,
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        question: 'Which number comes next: 2, 4, 6, 8, __?',
        options: ['9', '10', '11', '12'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Patterns',
        points: 1,
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        question: 'What is 10 + 5 - 3?',
        options: ['11', '12', '13', '14'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Mixed Operations',
        points: 1,
      },
      {
        id: 'q7',
        type: 'multiple_choice',
        question: 'How many sides does a triangle have?',
        options: ['2', '3', '4', '5'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Geometry',
        points: 1,
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        question: 'What is half of 16?',
        options: ['6', '7', '8', '9'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Division',
        points: 1,
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        question: 'Which is the largest number?',
        options: ['45', '54', '35', '43'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Number Comparison',
        points: 1,
      },
      {
        id: 'q10',
        type: 'multiple_choice',
        question: 'What is 7 + 7?',
        options: ['12', '13', '14', '15'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Addition',
        points: 1,
      },
    ],
  },

  // ============================================
  // LEVEL 2 - Basic Science (Easy)
  // ============================================
  {
    title: 'Living Things Around Us',
    description: 'Discover the basics of plants, animals, and nature',
    difficulty: 'easy',
    estimatedTime: 300,
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        question: 'What do plants need to grow?',
        options: ['Only water', 'Sunlight, water, and air', 'Only sunlight', 'Only soil'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Plants',
        points: 1,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        question: 'Which animal is known as the "King of the Jungle"?',
        options: ['Tiger', 'Lion', 'Bear', 'Elephant'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Animals',
        points: 1,
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        question: 'How many legs does a spider have?',
        options: ['6', '8', '10', '12'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Insects',
        points: 1,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        question: 'What color are most plants?',
        options: ['Blue', 'Red', 'Green', 'Yellow'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Plants',
        points: 1,
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        question: 'Which of these animals can fly?',
        options: ['Dog', 'Bird', 'Fish', 'Cat'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Animals',
        points: 1,
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        question: 'What do we call baby frogs?',
        options: ['Puppies', 'Kittens', 'Tadpoles', 'Chicks'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Animals',
        points: 1,
      },
      {
        id: 'q7',
        type: 'multiple_choice',
        question: 'Which sense do we use to see?',
        options: ['Touch', 'Hearing', 'Sight', 'Smell'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Human Body',
        points: 1,
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        question: 'What is the largest ocean on Earth?',
        options: ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Earth Science',
        points: 1,
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        question: 'Which of these is NOT a fruit?',
        options: ['Apple', 'Carrot', 'Banana', 'Orange'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Plants',
        points: 1,
      },
      {
        id: 'q10',
        type: 'multiple_choice',
        question: 'What do bees make?',
        options: ['Milk', 'Honey', 'Butter', 'Cheese'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Animals',
        points: 1,
      },
    ],
  },

  // ============================================
  // LEVEL 3 - English Basics (Easy)
  // ============================================
  {
    title: 'Words and Sentences',
    description: 'Build your foundation in English grammar and vocabulary',
    difficulty: 'easy',
    estimatedTime: 300,
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        question: 'What is the opposite of "hot"?',
        options: ['Warm', 'Cold', 'Cool', 'Freezing'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Antonyms',
        points: 1,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        question: 'Which word is a noun?',
        options: ['Run', 'Happy', 'Book', 'Quickly'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Parts of Speech',
        points: 1,
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        question: 'What is the plural of "child"?',
        options: ['Childs', 'Children', 'Childes', 'Childrens'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Grammar',
        points: 1,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        question: 'Choose the correct sentence:',
        options: ['She go to school.', 'She goes to school.', 'She going to school.', 'She goed to school.'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Grammar',
        points: 1,
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        question: 'What is a synonym for "happy"?',
        options: ['Sad', 'Joyful', 'Angry', 'Tired'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Synonyms',
        points: 1,
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        question: 'Which letter is a vowel?',
        options: ['B', 'C', 'E', 'F'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Alphabet',
        points: 1,
      },
      {
        id: 'q7',
        type: 'fill_blank',
        question: 'I ___ a student.',
        options: [],
        correctAnswers: [],
        correctAnswer: 'am',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Grammar',
        points: 1,
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        question: 'What punctuation mark ends a question?',
        options: ['Period (.)', 'Question mark (?)', 'Exclamation mark (!)', 'Comma (,)'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Punctuation',
        points: 1,
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        question: 'Which word means the same as "big"?',
        options: ['Small', 'Large', 'Tiny', 'Little'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Synonyms',
        points: 1,
      },
      {
        id: 'q10',
        type: 'multiple_choice',
        question: 'What is the past tense of "eat"?',
        options: ['Eated', 'Ate', 'Eaten', 'Eating'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Verb Tenses',
        points: 1,
      },
    ],
  },

  // ============================================
  // LEVEL 4 - General Knowledge (Easy-Medium)
  // ============================================
  {
    title: 'World Around Us',
    description: 'Explore interesting facts about our world',
    difficulty: 'easy',
    estimatedTime: 360,
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        question: 'How many days are there in a week?',
        options: ['5', '6', '7', '8'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Time',
        points: 1,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        question: 'What is the capital of France?',
        options: ['London', 'Berlin', 'Paris', 'Rome'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Geography',
        points: 1,
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        question: 'How many continents are there in the world?',
        options: ['5', '6', '7', '8'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Geography',
        points: 1,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        question: 'What color is the sky on a clear day?',
        options: ['Green', 'Blue', 'Red', 'Yellow'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Science',
        points: 1,
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        question: 'Which season comes after winter?',
        options: ['Summer', 'Spring', 'Fall', 'Autumn'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Seasons',
        points: 1,
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        question: 'What is the largest country in the world by area?',
        options: ['China', 'USA', 'Russia', 'Canada'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Geography',
        points: 1,
      },
      {
        id: 'q7',
        type: 'multiple_choice',
        question: 'How many hours are in a day?',
        options: ['12', '20', '24', '30'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Time',
        points: 1,
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        question: 'What do we use to measure temperature?',
        options: ['Ruler', 'Thermometer', 'Scale', 'Clock'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Measurement',
        points: 1,
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        question: 'Which ocean is between America and Europe?',
        options: ['Pacific', 'Indian', 'Atlantic', 'Arctic'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Geography',
        points: 1,
      },
      {
        id: 'q10',
        type: 'multiple_choice',
        question: 'What is the largest planet in our solar system?',
        options: ['Earth', 'Mars', 'Jupiter', 'Saturn'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Space',
        points: 1,
      },
    ],
  },

  // ============================================
  // LEVEL 5 - Philippine History Basics (Easy-Medium)
  // ============================================
  {
    title: 'Philippine Heroes',
    description: 'Learn about the brave heroes of the Philippines',
    difficulty: 'easy',
    estimatedTime: 360,
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        question: 'Who is known as the National Hero of the Philippines?',
        options: ['Andres Bonifacio', 'Jose Rizal', 'Emilio Aguinaldo', 'Apolinario Mabini'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'National Heroes',
        points: 1,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        question: 'What is the title of Jose Rizal\'s famous novel about Spanish colonization?',
        options: ['El Amor Patrio', 'Noli Me Tangere', 'La Solidaridad', 'Filipinas Dentro'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Literature',
        points: 1,
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        question: 'On what date do Filipinos celebrate Independence Day?',
        options: ['June 12', 'July 4', 'August 26', 'December 30'],
        correctAnswers: [0],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'National Holidays',
        points: 1,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        question: 'Who founded the Katipunan?',
        options: ['Jose Rizal', 'Emilio Aguinaldo', 'Andres Bonifacio', 'Marcelo H. del Pilar'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Organizations',
        points: 1,
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        question: 'What is the capital city of the Philippines?',
        options: ['Quezon City', 'Cebu', 'Manila', 'Davao'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 15,
        topic: 'Geography',
        points: 1,
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        question: 'Which country colonized the Philippines for more than 300 years?',
        options: ['USA', 'Japan', 'Spain', 'Portugal'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Colonial History',
        points: 1,
      },
      {
        id: 'q7',
        type: 'multiple_choice',
        question: 'What is the national flower of the Philippines?',
        options: ['Rose', 'Sampaguita', 'Sunflower', 'Gumamela'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'National Symbols',
        points: 1,
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        question: 'Where was Jose Rizal executed?',
        options: ['Luneta Park', 'Fort Santiago', 'Intramuros', 'Malacañang'],
        correctAnswers: [0],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Historical Sites',
        points: 1,
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        question: 'What does the three stars in the Philippine flag represent?',
        options: ['Three heroes', 'Three colors', 'Three major island groups', 'Three centuries'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'National Symbols',
        points: 1,
      },
      {
        id: 'q10',
        type: 'multiple_choice',
        question: 'Who was the first President of the Philippines?',
        options: ['Manuel L. Quezon', 'Emilio Aguinaldo', 'Jose P. Laurel', 'Manuel Roxas'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Government',
        points: 1,
      },
    ],
  },

  // ============================================
  // LEVEL 6 - Intermediate Math (Medium)
  // ============================================
  {
    title: 'Mathematical Thinking',
    description: 'Challenge yourself with fractions, decimals, and word problems',
    difficulty: 'medium',
    estimatedTime: 420,
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        question: 'What is 1/2 + 1/4?',
        options: ['1/6', '2/6', '3/4', '2/4'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 30,
        topic: 'Fractions',
        points: 1,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        question: 'What is 15% of 100?',
        options: ['10', '15', '20', '25'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Percentages',
        points: 1,
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        question: 'If a book costs ₱120 and is on sale for 25% off, what is the new price?',
        options: ['₱80', '₱90', '₱95', '₱100'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 35,
        topic: 'Word Problems',
        points: 1,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        question: 'What is the area of a rectangle with length 8 cm and width 5 cm?',
        options: ['13 cm²', '26 cm²', '40 cm²', '45 cm²'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 30,
        topic: 'Geometry',
        points: 1,
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        question: 'What is 0.5 + 0.25?',
        options: ['0.30', '0.55', '0.75', '0.80'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Decimals',
        points: 1,
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        question: 'If 3x = 15, what is x?',
        options: ['3', '5', '12', '18'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Algebra',
        points: 1,
      },
      {
        id: 'q7',
        type: 'multiple_choice',
        question: 'What is the perimeter of a square with side 6 cm?',
        options: ['12 cm', '18 cm', '24 cm', '36 cm'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Geometry',
        points: 1,
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        question: 'What is 2³ (2 to the power of 3)?',
        options: ['6', '8', '9', '12'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Exponents',
        points: 1,
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        question: 'Maria has 24 candies. She gives 1/3 to her brother. How many candies does she have left?',
        options: ['8', '12', '16', '18'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 35,
        topic: 'Word Problems',
        points: 1,
      },
      {
        id: 'q10',
        type: 'multiple_choice',
        question: 'What is the average of 10, 20, and 30?',
        options: ['15', '20', '25', '30'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Statistics',
        points: 1,
      },
    ],
  },

  // ============================================
  // LEVEL 7 - Science Exploration (Medium)
  // ============================================
  {
    title: 'Natural World',
    description: 'Dive deeper into biology, chemistry, and physics',
    difficulty: 'medium',
    estimatedTime: 420,
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        question: 'What is the process by which plants make their own food?',
        options: ['Respiration', 'Photosynthesis', 'Digestion', 'Fermentation'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Biology',
        points: 1,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        question: 'What is the chemical symbol for water?',
        options: ['O2', 'H2O', 'CO2', 'NaCl'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Chemistry',
        points: 1,
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        question: 'Which planet is closest to the Sun?',
        options: ['Venus', 'Earth', 'Mercury', 'Mars'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Astronomy',
        points: 1,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        question: 'What is the boiling point of water at sea level?',
        options: ['90°C', '100°C', '110°C', '120°C'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Physics',
        points: 1,
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        question: 'Which organ pumps blood throughout the body?',
        options: ['Brain', 'Lungs', 'Heart', 'Liver'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Human Body',
        points: 1,
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        question: 'What gas do humans breathe out?',
        options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Biology',
        points: 1,
      },
      {
        id: 'q7',
        type: 'multiple_choice',
        question: 'What is the center of an atom called?',
        options: ['Electron', 'Proton', 'Nucleus', 'Neutron'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Chemistry',
        points: 1,
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        question: 'Which force pulls objects toward the Earth?',
        options: ['Magnetism', 'Gravity', 'Friction', 'Tension'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Physics',
        points: 1,
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        question: 'What is the largest organ in the human body?',
        options: ['Heart', 'Brain', 'Skin', 'Liver'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Human Body',
        points: 1,
      },
      {
        id: 'q10',
        type: 'multiple_choice',
        question: 'What type of animal is a dolphin?',
        options: ['Fish', 'Mammal', 'Reptile', 'Amphibian'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Biology',
        points: 1,
      },
    ],
  },

  // ============================================
  // LEVEL 8 - English Mastery (Medium)
  // ============================================
  {
    title: 'Grammar and Composition',
    description: 'Master complex grammar rules and writing skills',
    difficulty: 'medium',
    estimatedTime: 420,
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        question: 'Which sentence is grammatically correct?',
        options: [
          'Me and John went to the store.',
          'John and I went to the store.',
          'John and me went to the store.',
          'I and John went to the store.'
        ],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Grammar',
        points: 1,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        question: 'What is the correct past participle of "write"?',
        options: ['Wrote', 'Written', 'Writed', 'Writing'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Verb Forms',
        points: 1,
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        question: 'Which word is an adverb?',
        options: ['Beautiful', 'Quickly', 'Happy', 'Running'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Parts of Speech',
        points: 1,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        question: 'What is the superlative form of "good"?',
        options: ['Gooder', 'Goodest', 'Better', 'Best'],
        correctAnswers: [3],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Adjectives',
        points: 1,
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        question: 'Which sentence uses correct subject-verb agreement?',
        options: [
          'The books on the table is mine.',
          'The books on the table are mine.',
          'The books on the table was mine.',
          'The books on the table be mine.'
        ],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 30,
        topic: 'Grammar',
        points: 1,
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        question: 'What is a metaphor?',
        options: [
          'A direct comparison using "like" or "as"',
          'A comparison without using "like" or "as"',
          'An exaggeration',
          'A sound word'
        ],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Figurative Language',
        points: 1,
      },
      {
        id: 'q7',
        type: 'fill_blank',
        question: 'She has ___ to the store. (go - past participle)',
        options: [],
        correctAnswers: [],
        correctAnswer: 'gone',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Verb Forms',
        points: 1,
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        question: 'Which is the correct use of "their/there/they\'re"? ___ going to the park.',
        options: ['Their', 'There', 'They\'re', 'Theyre'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Homophones',
        points: 1,
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        question: 'What type of sentence is this? "Stop!"',
        options: ['Declarative', 'Interrogative', 'Imperative', 'Exclamatory'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Sentence Types',
        points: 1,
      },
      {
        id: 'q10',
        type: 'multiple_choice',
        question: 'Which word is spelled correctly?',
        options: ['Recieve', 'Receive', 'Receve', 'Receeve'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Spelling',
        points: 1,
      },
    ],
  },

  // ============================================
  // LEVEL 9 - Advanced General Knowledge (Medium-Hard)
  // ============================================
  {
    title: 'World Culture and History',
    description: 'Test your knowledge of global events and cultures',
    difficulty: 'medium',
    estimatedTime: 480,
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        question: 'Which ancient civilization built the pyramids?',
        options: ['Romans', 'Greeks', 'Egyptians', 'Mayans'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Ancient History',
        points: 1,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        question: 'Who painted the famous artwork "Mona Lisa"?',
        options: ['Michelangelo', 'Leonardo da Vinci', 'Pablo Picasso', 'Vincent van Gogh'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Art',
        points: 1,
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        question: 'What is the smallest country in the world?',
        options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Geography',
        points: 1,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        question: 'In what year did World War II end?',
        options: ['1943', '1944', '1945', '1946'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Modern History',
        points: 1,
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        question: 'Which element has the chemical symbol "Au"?',
        options: ['Silver', 'Gold', 'Aluminum', 'Copper'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Chemistry',
        points: 1,
      },
      {
        id: 'q6',
        type: 'matching',
        question: 'Match the country with its capital city.',
        options: [],
        correctAnswers: [],
        correctAnswer: '',
        matchPairs: [
          { left: 'Japan', right: 'Tokyo' },
          { left: 'Australia', right: 'Canberra' },
          { left: 'Brazil', right: 'Brasília' },
          { left: 'Egypt', right: 'Cairo' }
        ],
        timeLimit: 45,
        topic: 'Geography',
        points: 1,
      },
      {
        id: 'q7',
        type: 'multiple_choice',
        question: 'Who invented the telephone?',
        options: ['Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'Benjamin Franklin'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Inventions',
        points: 1,
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        question: 'What is the largest desert in the world?',
        options: ['Sahara Desert', 'Arabian Desert', 'Gobi Desert', 'Antarctic Desert'],
        correctAnswers: [3],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 30,
        topic: 'Geography',
        points: 1,
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        question: 'Which musical instrument has 88 keys?',
        options: ['Organ', 'Piano', 'Accordion', 'Synthesizer'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Music',
        points: 1,
      },
      {
        id: 'q10',
        type: 'multiple_choice',
        question: 'What is the currency of Japan?',
        options: ['Won', 'Yuan', 'Yen', 'Ringgit'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 20,
        topic: 'Economics',
        points: 1,
      },
    ],
  },

  // ============================================
  // LEVEL 10 - Philippine History & Culture (Hard)
  // ============================================
  {
    title: 'Philippine Heritage',
    description: 'Deep dive into Philippine history, culture, and traditions',
    difficulty: 'hard',
    estimatedTime: 540,
    totalPoints: 10,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        question: 'What was the name of the first Filipino alphabet before Spanish colonization?',
        options: ['Abakada', 'Baybayin', 'Alibata', 'Tagalog Script'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 30,
        topic: 'Culture',
        points: 1,
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        question: 'Who wrote the Philippine national anthem "Lupang Hinirang"?',
        options: ['Julian Felipe', 'Jose Palma', 'Nicanor Abelardo', 'Francisco Santiago'],
        correctAnswers: [0],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 30,
        topic: 'National Symbols',
        points: 1,
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        question: 'What historic event is commemorated every April 9 in the Philippines?',
        options: ['Liberation Day', 'Bataan Day', 'Independence Day', 'EDSA Revolution'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 30,
        topic: 'Historical Events',
        points: 1,
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        question: 'Who was the first woman president of the Philippines?',
        options: ['Gloria Macapagal-Arroyo', 'Corazon Aquino', 'Imelda Marcos', 'Maria Ressa'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Government',
        points: 1,
      },
      {
        id: 'q5',
        type: 'matching',
        question: 'Match the Philippine region with its famous landmark.',
        options: [],
        correctAnswers: [],
        correctAnswer: '',
        matchPairs: [
          { left: 'Bohol', right: 'Chocolate Hills' },
          { left: 'Palawan', right: 'Underground River' },
          { left: 'Mayon', right: 'Perfect Cone Volcano' },
          { left: 'Banaue', right: 'Rice Terraces' }
        ],
        timeLimit: 50,
        topic: 'Geography',
        points: 1,
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        question: 'What was the codename of the operation to recapture Manila during WWII?',
        options: ['Operation Overlord', 'Operation Victor', 'Operation Musketeer', 'Operation Cartwheel'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 35,
        topic: 'World War II',
        points: 1,
      },
      {
        id: 'q7',
        type: 'multiple_choice',
        question: 'Which Philippine volcano erupted in 1991, one of the largest eruptions of the 20th century?',
        options: ['Mount Mayon', 'Taal Volcano', 'Mount Pinatubo', 'Mount Apo'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 30,
        topic: 'Natural Disasters',
        points: 1,
      },
      {
        id: 'q8',
        type: 'fill_blank',
        question: 'The Philippine Revolution against Spain began in the year ___.',
        options: [],
        correctAnswers: [],
        correctAnswer: '1896',
        matchPairs: [],
        timeLimit: 30,
        topic: 'Revolution',
        points: 1,
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        question: 'What is the traditional Filipino fighting art using sticks?',
        options: ['Karate', 'Taekwondo', 'Arnis', 'Kung Fu'],
        correctAnswers: [2],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 25,
        topic: 'Martial Arts',
        points: 1,
      },
      {
        id: 'q10',
        type: 'multiple_choice',
        question: 'Which treaty ended the Spanish-American War and transferred the Philippines to the US?',
        options: ['Treaty of Versailles', 'Treaty of Paris', 'Treaty of Biak-na-Bato', 'Treaty of Manila'],
        correctAnswers: [1],
        correctAnswer: '',
        matchPairs: [],
        timeLimit: 35,
        topic: 'Colonial History',
        points: 1,
      },
    ],
  },
];

/**
 * Level definitions with references to quiz IDs
 * These will be populated after quizzes are created
 */
const LEVEL_DEFINITIONS: Omit<Level, 'id' | 'unlocked' | 'completed' | 'stars'>[] = [
  {
    title: 'Numbers & Operations',
    description: 'Learn basic math operations and number patterns',
    quizId: '', // Will be filled after quiz creation
    gradient: ['#667eea', '#764ba2'],
    shardsReward: 5,
    xpReward: 50,
  },
  {
    title: 'Living Things',
    description: 'Explore plants, animals, and nature',
    quizId: '',
    gradient: ['#f093fb', '#f5576c'],
    shardsReward: 5,
    xpReward: 50,
  },
  {
    title: 'English Basics',
    description: 'Build your English vocabulary and grammar foundation',
    quizId: '',
    gradient: ['#4facfe', '#00f2fe'],
    shardsReward: 5,
    xpReward: 50,
  },
  {
    title: 'World Around Us',
    description: 'Discover interesting facts about our world',
    quizId: '',
    gradient: ['#43e97b', '#38f9d7'],
    shardsReward: 5,
    xpReward: 50,
  },
  {
    title: 'Philippine Heroes',
    description: 'Learn about the brave heroes of the Philippines',
    quizId: '',
    gradient: ['#fa709a', '#fee140'],
    requiredLevel: 2,
    shardsReward: 5,
    xpReward: 50,
  },
  {
    title: 'Mathematical Thinking',
    description: 'Challenge yourself with fractions and word problems',
    quizId: '',
    gradient: ['#30cfd0', '#330867'],
    requiredLevel: 3,
    shardsReward: 10,
    xpReward: 100,
  },
  {
    title: 'Natural World',
    description: 'Dive deeper into biology, chemistry, and physics',
    quizId: '',
    gradient: ['#a8edea', '#fed6e3'],
    requiredLevel: 3,
    shardsReward: 10,
    xpReward: 100,
  },
  {
    title: 'Grammar Mastery',
    description: 'Master complex grammar rules and writing skills',
    quizId: '',
    gradient: ['#ff9a9e', '#fecfef'],
    requiredLevel: 4,
    shardsReward: 10,
    xpReward: 100,
  },
  {
    title: 'World Culture',
    description: 'Test your knowledge of global events and cultures',
    quizId: '',
    gradient: ['#ffecd2', '#fcb69f'],
    requiredLevel: 5,
    shardsReward: 10,
    xpReward: 100,
  },
  {
    title: 'Philippine Heritage',
    description: 'Deep dive into Philippine history and culture',
    quizId: '',
    gradient: ['#ff6e7f', '#bfe9ff'],
    requiredLevel: 6,
    shardsReward: 15,
    xpReward: 150,
  },
];

/**
 * Main initialization function
 * Run this to populate your journey system
 */
export async function initializeJourneySystem() {
  try {
    console.log('🚀 Starting Journey System Initialization...');
    
    // Step 1: Create all quizzes
    console.log('\n📝 Creating journey quizzes...');
    const quizIds: string[] = [];
    
    for (let i = 0; i < JOURNEY_QUIZZES.length; i++) {
      const quiz = JOURNEY_QUIZZES[i];
      console.log(`\n[${i + 1}/${JOURNEY_QUIZZES.length}] Creating: ${quiz.title}`);
      console.log(`   Difficulty: ${quiz.difficulty}`);
      console.log(`   Questions: ${quiz.questions.length}`);
      
      // Use admin method
      const quizId = await JourneyService.createJourneyQuizAdmin(quiz);
      quizIds.push(quizId);
      console.log(`   ✅ Created with ID: ${quizId}`);
    }
    
    console.log('\n✅ All quizzes created successfully!');
    
    // Step 2: Update level definitions with quiz IDs
    console.log('\n📋 Preparing level definitions...');
    const levelsToCreate = LEVEL_DEFINITIONS.map((level, index) => ({
      ...level,
      id: index + 1,
      quizId: quizIds[index],
    }));
    
    // Step 3: Initialize levels in Firestore
    console.log('\n🏗️  Creating levels...');
    // Use admin method
    await JourneyService.initializeLevelsAdmin(levelsToCreate);
    
    // Step 4: Display summary
    console.log('\n📊 Initialization Summary:');
    console.log('═══════════════════════════════════════');
    console.log(`✓ Quizzes created: ${quizIds.length}`);
    console.log(`✓ Levels created: ${levelsToCreate.length}`);
    console.log(`✓ Total questions: ${JOURNEY_QUIZZES.reduce((sum, q) => sum + q.questions.length, 0)}`);
    console.log('═══════════════════════════════════════');
    
    console.log('\n🎉 Journey System initialized successfully!');
    console.log('Users can now start their educational journey.');
    
    return {
      success: true,
      quizIds,
      levelCount: levelsToCreate.length,
    };
  } catch (error) {
    console.error('\n❌ Error initializing journey system:', error);
    throw error;
  }
}

export async function verifyJourneySystem() {
  try {
    console.log('🔍 Verifying Journey System...');
    
    // Use admin methods
    const quizzes = await JourneyService.getAllJourneyQuizzesAdmin();
    const levels = await JourneyService.getAllLevelsAdmin();
    
    console.log('\n📊 System Status:');
    console.log('═══════════════════════════════════════');
    console.log(`Quizzes in database: ${quizzes.length}`);
    console.log(`Levels in database: ${levels.length}`);
    console.log('═══════════════════════════════════════');
    
    console.log('\n📚 Quiz List:');
    quizzes.forEach((quiz, index) => {
      console.log(`${index + 1}. ${quiz.title}`);
      console.log(`   Difficulty: ${quiz.difficulty}`);
      console.log(`   Questions: ${quiz.questions.length}`);
      console.log(`   ID: ${quiz.id}`);
    });
    
    console.log('\n🎮 Level List:');
    levels.forEach((level) => {
      console.log(`Level ${level.id}: ${level.title}`);
      console.log(`   Quiz ID: ${level.quizId}`);
      console.log(`   Rewards: ${level.shardsReward} shards, ${level.xpReward} XP`);
    });
    
    return { quizzes, levels };
  } catch (error) {
    console.error('❌ Error verifying journey system:', error);
    throw error;
  }
}

// Usage:
// import { initializeJourneySystem, verifyJourneySystem } from './scripts/initialize-journey';
//
// To initialize (run once):
// await initializeJourneySystem();
//
// To verify:
// await verifyJourneySystem();